# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-26 06:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0005_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, help_text='If you are not the author, enter the name or source here. This is needed for some licenses e.g. the CC-BY-SA.', max_length=100, null=True, verbose_name='Author')),
            ],
        ),
        migrations.AlterField(
            model_name='exercise',
            name='license_author',
            field=models.ForeignKey(default=60, help_text='If you are not the author, enter the name or source here. This is needed for some licenses e.g. the CC-BY-SA.', on_delete=django.db.models.deletion.CASCADE, to='exercises.Author'),
        ),
        migrations.AlterField(
            model_name='exerciseimage',
            name='license_author',
            field=models.ForeignKey(default=60, on_delete=django.db.models.deletion.CASCADE, to='exercises.Author'),
        ),
    ]
