# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-26 06:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0006_auto_20180626_0949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='author',
            new_name='license_author',
        ),
    ]
