# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-22 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0004_mealitem_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealitem',
            name='meal_category',
            field=models.CharField(choices=[(b'1', 'New meal'), (b'2', 'Previous meal')], default=b'1', max_length=20, verbose_name='Meal categories'),
        ),
    ]
