# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-26 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0005_mealitem_meal_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealitem',
            name='meal_category',
            field=models.CharField(choices=[('1', 'New meal'), ('2', 'Previous meal')], default='1', max_length=20, verbose_name='Meal categories'),
        ),
    ]
