# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-29 07:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0006_auto_20180626_0949'),
        ('nutrition', '0006_auto_20180626_1136'),
    ]

    operations = [
    ]
