# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-08 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0010_auto_20180608_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gymadminconfig',
            name='is_active',
        ),
        migrations.AddField(
            model_name='gymuserconfig',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Shows status of Gym members'),
        ),
    ]
