# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-09 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0011_auto_20180608_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymadminconfig',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Shows status of Gym members'),
        ),
    ]
