# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-09 14:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0012_gymadminconfig_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gymadminconfig',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='gymuserconfig',
            name='is_active',
        ),
    ]
