# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-09 14:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_userprofile_trainer_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='trainer_active',
        ),
    ]
