# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-11 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_userprofile_trainer_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_activated',
            field=models.BooleanField(default=True, verbose_name='Shows status of Gym members'),
        ),
    ]
