# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-20 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_userprofile_is_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='daysofweek',
            name='workout_plan',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
