# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-26 08:36
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0015_daysofweek_workout_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestAPIUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_on', models.DateTimeField(default=datetime.datetime(2018, 6, 26, 11, 36, 26, 911416))),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_user_creator', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_create_users',
            field=models.BooleanField(default=False),
        ),
    ]
