# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-26 10:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20180626_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restapiusers',
            name='registered_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 26, 13, 2, 45, 977669)),
        ),
    ]
