# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-31 19:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_auto_20180524_1451'),
        ('manager', '0008_auto_20180530_1412'),
    ]

    operations = [
    ]
