# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-20 07:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[(b'1', 'Default'), (b'2', 'Dropset')], default=b'1', max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='setting',
            name='reps',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(600)], verbose_name='Amount'),
        ),
        migrations.AddField(
            model_name='setting',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.WorkoutType'),
        ),
    ]
