# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-22 10:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_auto_20180620_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsession',
            name='logs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.WorkoutLog', verbose_name='Workout Log'),
        ),
        migrations.AlterField(
            model_name='workouttype',
            name='category',
            field=models.CharField(choices=[('1', 'Default'), ('2', 'Dropset')], default='1', max_length=10),
        ),
    ]
