# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-22 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_auto_20180620_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='cycle_type',
            field=models.CharField(choices=[('Microcycle', 'Microcycle - one week plan'), ('Mesocycle', 'Mesocycle - Two to six weeks plan'), ('Macrocycle', 'Macrocycle - one year plan')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='workouttype',
            name='category',
            field=models.CharField(choices=[('1', 'Default'), ('2', 'Dropset')], default='1', max_length=10),
        ),
    ]
