# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-19 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_importjsondocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='exported_from',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
