# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-21 06:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_auto_20180620_1044'),
        ('manager', '0012_auto_20180619_1451'),
    ]

    operations = [
    ]
