# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-21 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workouttype',
            name='category',
            field=models.CharField(choices=[('1', 'Default'), ('2', 'Dropset')], default='1', max_length=10),
        ),
    ]
