# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-25 08:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_auto_20180622_1228'),
        ('manager', '0015_merge'),
    ]

    operations = [
    ]
